version: "3"
networks:
  backend: 
    driver: bridge

services:
  app:
    image: 4da1ca9b0a7c
    environment:
      DB_URL: 'jdbc:postgresql://postgres:5432/root'
      DB_USER: 'root'
      DB_PASSWORD: 'root'
    networks:
      - backend
    ports:
      - 8080:8080
  postgres:
    image: postgres
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    networks:
      - backend
